# Example label mapping and filtering configuration for Neo4j to Neptune conversion
# This file demonstrates how to map vertex and edge labels and skip certain records during conversion

# Vertex label mappings
# Format: OldLabel: NewLabel
vertex_labels:
  Person: Individual
  Company: Organization
  Product: Item
  Location: Place
  User: Customer

# Edge label mappings
# Format: OLD_RELATIONSHIP_TYPE: NEW_RELATIONSHIP_TYPE
edge_labels:
  WORKS_FOR: EMPLOYED_BY
  LIVES_IN: RESIDES_IN
  OWNS: POSSESSES
  KNOWS: CONNECTED_TO
  PURCHASED: BOUGHT
  MANAGES: SUPERVISES

# Skip vertices configuration
# Input takes lists, can use alternative format, e.g. by_id: [1,2,3]
skip_vertices:
  # Skip vertices by their specific IDs
  by_id:
    - "vertex_123"
    - "vertex_456"
    - "user_999"

  # Skip vertices by their labels (any vertex with these labels will be skipped)
  by_label:
    - "TestData"
    - "Deprecated"
    - "TempNode"

# Skip edges configuration
skip_edges:
  # Skip edges by their relationship types
  # (Note: label only for edge as Neo4j default csv export doesn't include original edge IDs)
  by_label:
    - "TEMP_RELATIONSHIP"
    - "DEBUG_LINK"
    - "OLD_CONNECTION"
